"""
Export Download Service - Safe streaming of previously generated export files.

Phase 2-Step 16: Downloads CSV export files generated by export_generated audit records.
Uses audit log as source of truth. Validates path safety and batch ownership.
Does NOT mutate source data or call external systems.
"""

import logging
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional, Mapping, Any

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from .database_models import AuditLogRecord

logger = logging.getLogger(__name__)


class ExportDownloadError(Exception):
    """Base exception for export download operations."""
    pass


class ExportNotFoundError(ExportDownloadError):
    """Export audit record not found."""
    pass


class ExportAccessError(ExportDownloadError):
    """Export does not belong to the specified import batch."""
    pass


class ExportPathError(ExportDownloadError):
    """Export file path is unsafe or file is missing."""
    pass


@dataclass(frozen=True)
class ExportDownloadInfo:
    """Validated export download information."""
    import_id: str
    audit_log_id: int
    filename: str
    file_path: str
    content_type: str
    generated_at: datetime
    row_count: int
    warning_count: int


def _validate_path_safety(file_path: str, export_dir: str) -> bool:
    """
    Validate that file_path is safe and within export_dir.

    Checks:
    - Resolves symlinks and .. sequences
    - Verifies file is within export directory
    - Verifies file exists and is a regular file

    Returns:
        True if path is safe, False otherwise
    """
    try:
        export_path = Path(export_dir).resolve()
        file_path_resolved = Path(file_path).resolve()

        # Check if file is within export directory
        file_path_resolved.relative_to(export_path)

        # Check file exists and is a file
        if not file_path_resolved.exists():
            return False

        if not file_path_resolved.is_file():
            return False

        return True
    except (ValueError, OSError):
        # ValueError: file_path not relative to export_path
        # OSError: path resolution error
        return False


def get_export_download_info(
    import_id: str,
    audit_log_id: int,
    export_dir: str,
    config: Optional[Mapping[str, Any]] = None,
) -> ExportDownloadInfo:
    """
    Get validated export download information from audit log.

    Verifies:
    - Audit record exists with matching audit_log_id
    - Record belongs to import_id (batch_id)
    - action_type is "export_generated"
    - File path in details is safe and within export directory
    - File exists on disk

    Does NOT:
    - Mutate any data
    - Create audit records
    - Call external systems
    - Return file content (only metadata and path)

    Args:
        import_id: Import batch ID
        audit_log_id: Audit log record ID
        export_dir: Configured export directory (absolute path)
        config: Optional database configuration

    Returns:
        ExportDownloadInfo with validated metadata and path

    Raises:
        ExportNotFoundError: If audit record not found
        ExportAccessError: If record doesn't belong to import_id or isn't export_generated
        ExportPathError: If file path is unsafe or file doesn't exist
        ValueError: If database config invalid
    """
    if not config:
        config = {}

    # Get database URL
    database_url = config.get('GIVEBUTTER_DATABASE_URL')
    if not database_url:
        import os
        database_url = os.environ.get('GIVEBUTTER_DATABASE_URL')

    if not database_url:
        raise ValueError(
            "Export download requires database configuration. "
            "Set GIVEBUTTER_DATABASE_URL environment variable or pass config."
        )

    # Create database session
    engine = create_engine(database_url, echo=False)
    SessionLocal = sessionmaker(bind=engine)
    session = SessionLocal()

    try:
        # Get audit record
        record = session.query(AuditLogRecord).filter_by(
            id=audit_log_id
        ).first()

        if not record:
            raise ExportNotFoundError(
                f"No export record found with ID {audit_log_id}"
            )

        # Verify batch ownership
        if record.batch_id != import_id:
            raise ExportAccessError(
                f"Export record does not belong to import {import_id}"
            )

        # Verify action type
        if record.action_type != "export_generated":
            raise ExportAccessError(
                f"Record is not an export (action_type={record.action_type})"
            )

        # Extract details
        if not record.details:
            raise ExportPathError("Export record has no details")

        details = record.details
        filename = details.get('filename')
        file_path = details.get('file_path')
        row_count = details.get('row_count', 0)
        warning_count = details.get('warning_count', 0)

        if not filename or not file_path:
            raise ExportPathError("Export record missing filename or file_path")

        # Validate path safety
        if not _validate_path_safety(file_path, export_dir):
            raise ExportPathError(
                f"Export file path is unsafe or file does not exist"
            )

        logger.info(
            f"Validated export download: {import_id} audit={audit_log_id} "
            f"file={filename}"
        )

        return ExportDownloadInfo(
            import_id=import_id,
            audit_log_id=audit_log_id,
            filename=filename,
            file_path=file_path,
            content_type="text/csv",
            generated_at=record.action_timestamp,
            row_count=row_count,
            warning_count=warning_count,
        )

    finally:
        session.close()
